spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/Workspace/chimhahademo/chim
    username: chimhaha
    password: 11
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      use-new-id-generator-mappings: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:h2-data.sql
logging:
  level:
    org:
      hibernate:
        start: debug


